In [1]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(24).reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [6]:
np.array([[2,2,2,2],[1,1,1,1]])

array([[2, 2, 2, 2],
       [1, 1, 1, 1]])

variable.ndim -->obtiene dimensiones

variable.shape -->obtiene cantidad de filas, columnas

variable.dtype -->tipo de dato

variable.itemsize -->tamaño en bytes

np.zeros(nfil,ncol)

np.ones(nfil,ncol)

np.full((nfil,ncol),numero, dtype='float32') llena con numero la matriz de dimensiones indicadas, se puede especificar tipo de dato

np.full_like(variable_con_dimension, valor) llena con valor en dimensiones iguales a elemento pasado

np.full(variable.shape, valor) llena con valor en dimensiones igual a otra variable

np.random.rand(4,2) crea matriz de dimensiones indicadas con numeros aleatorios entre cero y uno

In [8]:
np.full(shape = (5,5), fill_value = 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [11]:
base = np.linspace(2, 6, 10) #arreglo que vaya de 2 a 6 y tenga 10 elem
base

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [13]:
np.full_like(base, np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265,
       3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

In [16]:
np.random.rand(2,5)

array([[0.15049919, 0.01674351, 0.9579124 , 0.14470707, 0.6782935 ],
       [0.73803322, 0.30767339, 0.77716759, 0.22402145, 0.20185827]])

In [25]:
np.random.uniform(low = 1, high=2, size=5)

array([1.48503969, 1.46919003, 1.82201278, 1.86192325, 1.25091457])

In [26]:
np.random.normal(loc = 0, scale = 2, size = 10)

array([ 2.5327517 ,  1.50200291, -1.99600464,  0.72214203,  1.54925333,
       -0.91575568,  1.2145576 , -0.03731102, -2.61210431,  1.92208541])

In [29]:
a = np.arange(8).reshape(2,2,2)
b = np.arange(8).reshape(2,2,2)
print(a*b)
print("....")
print(a)
print(b)

[[[ 0  1]
  [ 4  9]]

 [[16 25]
  [36 49]]]
....
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [34]:
matriz_a = np.mat(([2,2],[2,3]))

In [36]:
matriz_a

matrix([[2, 2],
        [2, 3]])

In [35]:
matriz_a.I

matrix([[ 1.5, -1. ],
        [-1. ,  1. ]])

In [38]:
matriz_a * matriz_a.I

matrix([[1., 0.],
        [0., 1.]])

In [39]:
%%timeit
a = np.arange(1000)
b = np.ones(1000)
a+b

20.7 µs ± 3.55 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
